import "./globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main class="px-4 py-6 md:px-6 lg:px-8">{children}</main>
      </body>
    </html>
  );
}
